package pt.ulisboa.tecnico.rnl.dei.dms.person.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import pt.ulisboa.tecnico.rnl.dei.dms.exceptions.DEIException;
import pt.ulisboa.tecnico.rnl.dei.dms.exceptions.ErrorMessage;
import pt.ulisboa.tecnico.rnl.dei.dms.person.domain.Person;
import pt.ulisboa.tecnico.rnl.dei.dms.person.dto.PersonDto;
import pt.ulisboa.tecnico.rnl.dei.dms.person.repository.PersonRepository;
import pt.ulisboa.tecnico.rnl.dei.dms.studentEnrollment.domain.StudentEnrollment;
import pt.ulisboa.tecnico.rnl.dei.dms.studentEnrollment.repository.StudentEnrollmentRepository;

import org.apache.commons.validator.routines.EmailValidator;

// Service class for managing Person entities
@Service
@Transactional
public class PersonService {

	@Autowired
	private PersonRepository personRepository;
	
	@Autowired
	private StudentEnrollmentRepository studentEnrollmentRepository;

	private Person fetchPersonOrThrow(long id) {
		return personRepository.findById(id)
				.orElseThrow(() -> new DEIException(ErrorMessage.NO_SUCH_PERSON, Long.toString(id)));
	}

	private boolean isValidEmail(String email) {
    	return EmailValidator.getInstance().isValid(email);
	}

	@Transactional
	public List<PersonDto> getPeople() {
		return personRepository.findAll().stream()
				.map(PersonDto::new)
				.toList();
	}

	@Transactional
	public PersonDto createPerson(PersonDto personDto) {
		if (personDto.name() == null || personDto.name().isBlank()) {
			throw new DEIException(ErrorMessage.PERSON_NAME_NOT_VALID);
			
		} else if (personDto.email() == null || personDto.email().isBlank() || !isValidEmail(personDto.email())) {
			throw new DEIException(ErrorMessage.PERSON_EMAIL_NOT_VALID, personDto.email());

		} else if (personDto.type() == null || personDto.type().isBlank()) {
			throw new DEIException(ErrorMessage.PERSON_TYPE_NOT_VALID);

		} else if (personRepository.existsByIstId(personDto.istId())) {
			throw new DEIException(ErrorMessage.PERSON_ALREADY_EXISTS, personDto.istId());

		} else if (personRepository.existsByEmail(personDto.email())) {
			throw new DEIException(ErrorMessage.EMAIL_ALREADY_EXISTS, personDto.email());
		}
		Person person = new Person(personDto);
		person.setId(null); // to ensure that the id is generated by the database
		return new PersonDto(personRepository.save(person));
	}

	@Transactional
	public PersonDto getPerson(long id) {
		return new PersonDto(fetchPersonOrThrow(id));
	}

	@Transactional
	public PersonDto updatePerson(long id, PersonDto personDto) {
		fetchPersonOrThrow(id); // ensure exists

		// FIXME: hmmm, updatePerson and createPerson are very similar
		// maybe we should refactor this? have a
		// `private PersonDto something(Long id, PersonDto personDto)` method?
		// ...or maybe not... who knows...
		Person person = new Person(personDto);
		person.setId(id);
		return new PersonDto(personRepository.save(person));
	}

	@Transactional
	public void deletePerson(long id) {
		fetchPersonOrThrow(id); // ensure exists
		
		// Get all student enrollments for this person
		List<StudentEnrollment> enrollments = studentEnrollmentRepository.findByStudentId(id);
		
		// Delete student enrollments (this will cascade delete evaluation grades)
		for (StudentEnrollment enrollment : enrollments) {
			studentEnrollmentRepository.delete(enrollment);
		}
		
		// TODO: Handle cases where person is a main teacher or assistant teacher
		// You might want to prevent deletion or reassign curricularUnits
		
		// Finally, delete the person
		personRepository.deleteById(id);
	}
}
