package pt.ulisboa.tecnico.rnl.dei.dms.course.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import pt.ulisboa.tecnico.rnl.dei.dms.exceptions.DEIException;
import pt.ulisboa.tecnico.rnl.dei.dms.exceptions.ErrorMessage;
import pt.ulisboa.tecnico.rnl.dei.dms.course.domain.Course;
import pt.ulisboa.tecnico.rnl.dei.dms.course.dto.CourseDto;
import pt.ulisboa.tecnico.rnl.dei.dms.course.repository.CourseRepository;

// Service class for managing Course entities
@Service
@Transactional
public class CourseService {

    @Autowired
    private CourseRepository courseRepository;

    private Course fetchCourseOrThrow(long id) {
        return courseRepository.findById(id)
                .orElseThrow(() -> new DEIException(ErrorMessage.NO_SUCH_COURSE, Long.toString(id)));
    }

    @Transactional
    public List<CourseDto> getCourses() {
        return courseRepository.findAll().stream()
                .map(CourseDto::new)
                .toList();
    }

    @Transactional
    public CourseDto createCourse(CourseDto courseDto) {
        if (courseDto.code() == null || courseDto.code().isBlank()) {
            throw new DEIException(ErrorMessage.COURSE_CODE_NOT_VALID);
            
        } else if (courseDto.name() == null || courseDto.name().isBlank()) {
            throw new DEIException(ErrorMessage.COURSE_NAME_NOT_VALID);

        } else if (courseRepository.existsByCode(courseDto.code())) {
            throw new DEIException(ErrorMessage.COURSE_ALREADY_EXISTS, courseDto.code());

        } else if (courseRepository.existsByName(courseDto.name())) {
            throw new DEIException(ErrorMessage.COURSE_NAME_ALREADY_EXISTS, courseDto.name());
        }
        
        Course course = new Course(courseDto);
        course.setId(null); // to ensure that the id is generated by the database
        return new CourseDto(courseRepository.save(course));
    }

    @Transactional
    public CourseDto getCourse(long id) {
        return new CourseDto(fetchCourseOrThrow(id));
    }

    @Transactional
    public CourseDto updateCourse(long id, CourseDto courseDto) {
        fetchCourseOrThrow(id); // ensure exists

        Course course = new Course(courseDto);
        course.setId(id);
        return new CourseDto(courseRepository.save(course));
    }

    @Transactional
    public void deleteCourse(long id) {
        fetchCourseOrThrow(id); // ensure exists

        courseRepository.deleteById(id);
    }
}